dev/dev/Models/Pilote.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Pilote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pilote()
        {
            this.Vol = new HashSet<Vol>();
        }
    
        public int num_pil { get; set; }
        [Required]
        public string nom_pil { get; set; }
        [Required]
        [MaxLength(10)]
        public string prenom_pil { get; set; }
        [MaxLength(10)]
        [Required]
        public string ville_domicile { get; set; }
        [Required]
        [Phone]
        public int num_tel { get; set; }
        
        [Required]
        [EmailAddress]
        
        public string email { get; set; }
        [Required]
        public Nullable<int> salaire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vol> Vol { get; set; }
    }
}

dev/dev/Controllers/PilotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using dev.Models;

namespace dev.Controllers
{
    public class PilotesController : Controller
    {
        private BD_aeroportEntities db = new BD_aeroportEntities();

        // GET: Pilotes
        public ActionResult Index()
        {
            //var pquery = db.Pilote.Where(elt => elt.nom_pil.Contains("i")).ToList();
            // var pquery = db.Pilote.Where(elt => elt.ville_domicile == "Rabat" && elt.salaire > 18000).ToList();
            //var pquery = db.Pilote.OrderByDescending(c => c.salaire);
            // var pquery = db.Vol.Where(elt=> elt.date_depart.CompareTo(new DateTime(2017,9,1)) < 0 && elt.date_depart.CompareTo(new DateTime(2017, 9, 1))>0);
            //var pquery = db.Pilote.Where(elt => (elt.salaire < 20000) && (elt.ville_domicile == "casablanca")).ToList();
            var pquery = from pi in db.Pilote 
                         join vo in db.Vol 
                         on pi.num_pil equals vo.num_pil
                         where (vo.ville_depart == "rabat" && (vo.ville_arrive == "Paris" || vo.ville_arrive == "Madrid"))
                         select pi
                         ;
            
            ViewData["max"] = db.Pilote.Max(elt => elt.salaire).ToString();
            ViewData["min"] = db.Pilote.Min(elt => elt.salaire).ToString();
            ViewData["moyenne"] = db.Pilote.Average(elt => elt.salaire).ToString();
            ViewData["total"] = db.Pilote.Sum(elt => elt.salaire).ToString();
           


            return View(db.Pilote.ToList());
        }
        public ActionResult Trier()
        {
            var query = from pi in db.Pilote orderby pi.ville_domicile, pi.salaire select pi;
            return View(query.ToList());
        }
        

        // GET: Pilotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilote pilote = db.Pilote.Find(id);
            if (pilote == null)
            {
                return HttpNotFound();
            }
            return View(pilote);
        }

        // GET: Pilotes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pilotes/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "num_pil,nom_pil,prenom_pil,ville_domicile,num_tel,email,salaire")] Pilote pilote)
        {
            if (ModelState.IsValid)
            {
                db.Pilote.Add(pilote);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pilote);
        }

        // GET: Pilotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilote pilote = db.Pilote.Find(id);
            if (pilote == null)
            {
                return HttpNotFound();
            }
            return View(pilote);
        }

        // POST: Pilotes/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "num_pil,nom_pil,prenom_pil,ville_domicile,num_tel,email,salaire")] Pilote pilote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pilote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pilote);
        }

        // GET: Pilotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pilote pilote = db.Pilote.Find(id);
            if (pilote == null)
            {
                return HttpNotFound();
            }
            return View(pilote);
        }

        // POST: Pilotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pilote pilote = db.Pilote.Find(id);
            db.Pilote.Remove(pilote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dev/dev/Views/Pilotes/Create.cshtml
@model dev.Models.Pilote

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pilote</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom_pil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_pil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_pil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom_pil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom_pil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom_pil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ville_domicile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ville_domicile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ville_domicile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num_tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num_tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num_tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.salaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.salaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.salaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dev/dev/Views/Pilotes/Delete.cshtml
@model dev.Models.Pilote

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pilote</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_pil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_pil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom_pil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom_pil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ville_domicile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ville_domicile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num_tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salaire)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

dev/dev/Views/Pilotes/Details.cshtml
@model dev.Models.Pilote

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pilote</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_pil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_pil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom_pil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom_pil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ville_domicile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ville_domicile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num_tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.salaire)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.salaire)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.num_pil }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dev/dev/Views/Pilotes/Edit.cshtml
@model dev.Models.Pilote

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pilote</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.num_pil)

        <div class="form-group">
            @Html.LabelFor(model => model.nom_pil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_pil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_pil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom_pil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom_pil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom_pil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ville_domicile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ville_domicile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ville_domicile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num_tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num_tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num_tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.salaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.salaire, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.salaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dev/dev/Views/Pilotes/Index.cshtml
@model IEnumerable<dev.Models.Pilote>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
    <a class="btn btn-primary" href=@Url.Action("Trier","Pilotes") value="trier">trier  </a>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_pil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prenom_pil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ville_domicile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.num_tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.salaire)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_pil)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prenom_pil)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ville_domicile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.num_tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.salaire)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.num_pil }) |
            @Html.ActionLink("Details", "Details", new { id=item.num_pil }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.num_pil })
        </td>
    </tr>
}

</table>

max     : @ViewData["max"];
min     : @ViewData["min"];
moyenne : @ViewData["moyenne"];
total   : @ViewData["total"];

@{
    var query = Model.GroupBy(elt => elt.ville_domicile, (Ville, Salaire) => new { VILLE = Ville, SALAIRE = Salaire.Average(e => e.salaire) });

    <div>VILLE => moyenne des salaire</div>
    foreach(var item in query)
    {
    <div> @item.VILLE => @item.SALAIRE </div>
    }


    
}

dev/dev/Views/Pilotes/Trier.cshtml
@model IEnumerable<dev.Models.Pilote>

@{
    ViewBag.Title = "Trier";
}

<h2>Trier</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_pil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prenom_pil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ville_domicile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.num_tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.salaire)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_pil)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prenom_pil)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ville_domicile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.num_tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.salaire)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.num_pil }) |
            @Html.ActionLink("Details", "Details", new { id=item.num_pil }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.num_pil })
        </td>
    </tr>
}

</table>

dev/dev/Views/Pilotes/test.cshtml
@model dev.Models.Pilote
@{
    ViewBag.Title = "test";



}

<h2>test</h2>