WebApplication1/WebApplication1/Models/utilisateur.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public utilisateur()
        {
            this.review = new HashSet<review>();
            this.u_application = new HashSet<u_application>();
        }
    
        public int id_user { get; set; }
        [Display(Name ="Username")]
        [Required]
        
        public string nom_utilisateur { get; set; }
        [Display(Name = "Email")]
        [Required]
        [EmailAddress]
        public string email { get; set; }
        [Required]
        [MaxLength(50)]
        [Display(Name ="Last Name")]
        public string nom { get; set; }
        [Required]
        [MaxLength(50)]
        [Display(Name ="First Name")]
        public string prenom { get; set; }
        [Required]
        [Display (Name ="Birth day Date")]
        public System.DateTime date_naissance { get; set; }

        [MinLength(length:8)]
        [MaxLength(64,ErrorMessage ="MAX LENGTH IS 64 CHAR")]
        [Required]
        [Display (Name = "Password")]
        public string motdepasse { get; set; }
        
        public string u_role { get; set; }
        public int bibliotheque_id_bib { get; set; }
    
        public virtual bibliotheque bibliotheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> review { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<u_application> u_application { get; set; }
    }
}

WebApplication1/WebApplication1/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class UtilisateursController : Controller
    {
        private profinsemEntities db = new profinsemEntities();

        // GET: utilisateurs
        public ActionResult Index()
        {
            if ((string)Session["role"] != "Admin")
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "vous avez pas les droits");

            return View(db.utilisateur.ToList());
        }

        // GET: utilisateurs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utilisateur utilisateur = db.utilisateur.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        // GET: utilisateurs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: utilisateurs/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_user,nom_utilisateur,email,nom,prenom,date_naissance,motdepasse")] utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                utilisateur.u_role = "user";
                utilisateur.date_naissance = utilisateur.date_naissance.Date;
                bibliotheque bib = new bibliotheque();
                bib.utilisateur.Add(utilisateur);
                utilisateur.bibliotheque = bib;
                db.utilisateur.Add(utilisateur);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(utilisateur);
        }

        // GET: utilisateurs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utilisateur utilisateur = db.utilisateur.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        // POST: utilisateurs/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_user,nom_utilisateur,email,nom,prenom,date_naissance,motdepasse,u_role")] utilisateur utilisateur)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(utilisateur).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(utilisateur);
        }

        // GET: utilisateurs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            utilisateur utilisateur = db.utilisateur.Find(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }

        // POST: utilisateurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            utilisateur utilisateur = db.utilisateur.Find(id);
            db.utilisateur.Remove(utilisateur);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Login()
        {
            ViewBag.connect = "";
            string username = Request.Form["nom_utilisateur"];
            string password = Request.Form["mot_de_passe"];
            utilisateur user = null;
            try
            {
              user = db.utilisateur.Where(c => c.nom_utilisateur == username && c.motdepasse == password).First();
                Session["user"] = user;
                Session["user_id"] = user.id_user;  
                Session["role"] = user.u_role;
            }catch(System.InvalidOperationException )
            {
                user = null;ViewBag.connect = "Error";return View();
            }
            
           
             
            return RedirectToAction("index", "u_application");
        }
        public ActionResult deconnexion()
        {
            Session["user"] = null;
            Session.Clear();
            return RedirectToAction("Login");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/utilisateurs/Create.cshtml
@model WebApplication1.Models.utilisateur

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>utilisateur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom_utilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_utilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_utilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_naissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_naissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_naissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.motdepasse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.motdepasse, htmlAttributes: new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.motdepasse, "", new { @class = "text-danger" })
            </div>
        </div>

 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/utilisateurs/Delete.cshtml
@model WebApplication1.Models.utilisateur

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>utilisateur</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_utilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_utilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_naissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.motdepasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.motdepasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.u_role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.u_role)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/WebApplication1/Views/utilisateurs/Details.cshtml
@model WebApplication1.Models.utilisateur

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>utilisateur</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_utilisateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_utilisateur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_naissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_naissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.motdepasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.motdepasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.u_role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.u_role)
        </dd>
        <dt>
            Application owned :
        </dt>
        @foreach(var item in Model.u_application)
        {
            Html.ActionLink(item.nom_app, "details", "u_application", new { id = item.id_app });
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_user }) |
    @Html.ActionLink("Delete","Delete",new {id = Model.id_user})|
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/WebApplication1/Views/utilisateurs/Edit.cshtml
@model WebApplication1.Models.utilisateur

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>utilisateur</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_user)

        <div class="form-group">
            @Html.LabelFor(model => model.nom_utilisateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_utilisateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_utilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_naissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_naissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_naissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.motdepasse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.motdepasse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.motdepasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.u_role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.u_role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.u_role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/WebApplication1/Views/utilisateurs/Index.cshtml
@model IEnumerable<WebApplication1.Models.utilisateur>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_utilisateur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prenom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date_naissance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.motdepasse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.u_role)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_utilisateur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prenom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date_naissance.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.motdepasse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.u_role)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_user }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_user }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_user })
        </td>
    </tr>
}

</table>

WebApplication1/WebApplication1/Views/utilisateurs/Login.cshtml
@model WebApplication1.Models.utilisateur
@{
    ViewBag.Title = "Login";
   
}
<link href="~/Content/StyleSheet2.css" rel="stylesheet" />

<form method="post" action=@Url.Action("Login","Utilisateurs")>
    <div class="form-group">
        
        <input type="text" name="nom_utilisateur" placeholder="Username"  class="form-control" />
    </div>
    <div class="form-group">
        
        <input type="password" name="mot_de_passe" placeholder="Password"  class="form-control" />
    </div>

  

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-default" />
        </div>
    </div>

</form>