dev/dev/Models/Avion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dev.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avion()
        {
            this.Vol = new HashSet<Vol>();
        }
        [Required] 
        public int num_av { get; set; }
        [Required]
        public string nom_av { get; set; }
        
        [Required]
        public int capacite { get; set; }
        [Required]
        public string localisation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vol> Vol { get; set; }
    }
}

dev/dev/Controllers/AvionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dev.Models;

namespace dev.Controllers
{
    public class AvionsController : Controller
    {
        private BD_aeroportEntities db = new BD_aeroportEntities();

        // GET: Avions
        public ActionResult Index()
        {


         
            
            
            
            
            return View(db.Avion.ToList());
        }


        public ActionResult Trier()
        {
            var pquery = from av in db.Avion orderby av.capacite select av;
            return View(pquery.ToList());
        }


        // GET: Avions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avion avion = db.Avion.Find(id);
            if (avion == null)
            {
                return HttpNotFound();
            }
            return View(avion);
        }

        // GET: Avions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Avions/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "num_av,nom_av,capacite,localisation")] Avion avion)
        {
            if (ModelState.IsValid)
            {
                db.Avion.Add(avion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(avion);
        }

        // GET: Avions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avion avion = db.Avion.Find(id);
            if (avion == null)
            {
                return HttpNotFound();
            }
            return View(avion);
        }

        // POST: Avions/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "num_av,nom_av,capacite,localisation")] Avion avion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(avion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(avion);
        }

        // GET: Avions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avion avion = db.Avion.Find(id);
            if (avion == null)
            {
                return HttpNotFound();
            }
            return View(avion);
        }

        // POST: Avions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Avion avion = db.Avion.Find(id);
            db.Avion.Remove(avion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dev/dev/Views/Avions/Create.cshtml
@model dev.Models.Avion

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Avion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nom_av, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_av, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_av, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.capacite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.capacite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.capacite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.localisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.localisation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dev/dev/Views/Avions/Delete.cshtml
@model dev.Models.Avion

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Avion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_av)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_av)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.capacite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.capacite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.localisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.localisation)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

dev/dev/Views/Avions/Details.cshtml
@model dev.Models.Avion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Avion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nom_av)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom_av)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.capacite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.capacite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.localisation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.localisation)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.num_av }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dev/dev/Views/Avions/Edit.cshtml
@model dev.Models.Avion

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Avion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.num_av)

        <div class="form-group">
            @Html.LabelFor(model => model.nom_av, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom_av, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom_av, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.capacite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.capacite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.capacite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.localisation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.localisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.localisation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dev/dev/Views/Avions/Index.cshtml
@model IEnumerable<dev.Models.Avion>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<a class="btn btn-primary" href=@Url.Action("Trier","Avions")>trier</a>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_av)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.capacite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.localisation)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_av)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.capacite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.localisation)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.num_av }) |
            @Html.ActionLink("Details", "Details", new { id=item.num_av }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.num_av })
        </td>
    </tr>
}

</table>

dev/dev/Views/Avions/Trier.cshtml
@model IEnumerable<dev.Models.Avion>

@{
    ViewBag.Title = "Trier";
}

<h2>Trier</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nom_av)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.capacite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.localisation)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom_av)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.capacite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.localisation)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.num_av }) |
            @Html.ActionLink("Details", "Details", new { id=item.num_av }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.num_av })
        </td>
    </tr>
}

</table>